repos:
- repo: https://github.com/psf/black
  rev: 23.3.0
  hooks:
  - id: black
    language_version: python3
            # Only run on Python files in specific directories/files.
    files: ^(loadcfg/|tests/|docs/|setup\.py)
    args: [--line-length, '110']

- repo: https://github.com/PyCQA/isort
  rev: 5.12.0
  hooks:
  - id: isort
    language_version: python3
    files: ^(loadcfg/|tests/|docs/|setup\.py)

- repo: https://github.com/charliermarsh/ruff-pre-commit
  rev: v0.0.241
  hooks:
  - id: ruff
    language_version: python3
    files: \.py$
    args: [--fix, --line-length, '110']

- repo: https://github.com/igorshubovych/markdownlint-cli
  rev: v0.34.0
  hooks:
  - id: markdownlint
    files: \.md$

- repo: local
  hooks:
  - id: yamlfmt
    name: yamlfmt
    entry: yamlfmt -w
    language: python
    files: \.(ya?ml)$
