name: PR Installation Instructions

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  issues: write

jobs:
  comment:
    runs-on: ubuntu-latest

    steps:
    - name: Post installation instructions comment
      uses: peter-evans/create-or-update-comment@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        issue-number: ${{ github.event.pull_request.number }}
        body: |
          **Installation Instructions for this PR Branch**

          You can install this branch of **loadcfg** directly from GitHub using pip. Simply run:

          ```bash
          pip install git+https://github.com/danielkorkin/loadcfg.git@${{ github.head_ref }}
          ```

          This command installs the code from the branch **${{ github.head_ref }}** of the repository.
