name: Test and Codecov

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    name: Run tests and upload coverage
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
          # Fetch full git history so Codecov can get accurate diff and commit details.
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    - name: Upgrade pip and install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-dev.txt
        # Install in editable mode so that coverage maps to your repo files
        pip install -e .

    - name: Run tests with coverage
      run: |
        # Run tests with branch coverage and output an XML report (coverage.xml)
        pytest --maxfail=1 --disable-warnings --cov=loadcfg --cov-branch --cov-report=xml

    - name: List coverage report file
      run: ls -la

    - name: Upload coverage to Codecov
      if: always()
      uses: codecov/codecov-action@v5
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
